### ISSUE TITLE
async code support

### ISSUE THREAD

**Issue by 0x8f701** [bluss/bencher#16]
Can we offer an async_std/tokio runtime out of box? It seems run `block_on` in `b.iter` will not be able to know the real result because it has been affected by async_std/tokio runtime

**Comment by bluss** [comment]
This project is in maint mode and there is no feature development (see repo description). Thanks 🙂

**Comment by 0x8f701** [comment]
It's not clear from README please otherwise archive it.

**Comment by 0x8f701** [comment]
@bluss Finally found on description, please move it to README thanks
