### ISSUE TITLE
Failed if benchmark file named as bench.rs

### ISSUE THREAD

**Issue by vbuell** [bluss/bencher#8]
Step to reproduce:

Create some simple  benchmark file in `benches/bench.rs`. Put in Cargo.toml:

```
[[bench]]
name = "bench"
harness = false
```

Cargo failed with the error:
```
error: couldn't read "src/bench.rs": No such file or directory (os error 2)
error: Could not compile `benchmark_templates`.
```

Note that it tries to read benchmark file from `src/` directory. Strangely enough that it fails only if file named as bench.rs. Any other name I tried worked ok - if to change the name to "bench_" in Cargo.toml, it look the file in `benches` directory:

```
error: couldn't read "benches/bench_.rs": No such file or directory (os error 2)
error: Could not compile `benchmark_templates`.
```

**Comment by sunjay** [comment]
Also experienced this! Thank you for filing the issue I had no idea it was the filename. :open_mouth:

**Comment by bluss** [comment]
Likely a cargo issue, don't know what this crate can do about it.

**Comment by sunjay** [comment]
I opened an issue for this in Cargo here: https://github.com/rust-lang/cargo/issues/3932

**Comment by bluss** [comment]
Fixed in cargo :+1:
