### ISSUE TITLE
Support Request: Can I run #[test] tests within bencher?

### ISSUE THREAD

**Issue by jordanbray** [bluss/bencher#9]
I have been duplicating all my `#[test]`s within bencher, but I notice that, once bencher completes, it lists every `#[test]` I have and marks it as ignored.
In my case, all my benchmarks are exactly the same as my `#[test]`s.
Is there an officially supported way to run `#[test]`s within bencher, or should I make some boilerplate stuff to remove my code duplication?
Thanks.

**Comment by bluss** [comment]
Hi, sorry for getting back to you so late. It's not in the scope of this crate to run tests, are you sure you are using bencher for this? I sounds like regular Rust `#[test]` support.

I would organize it so that bencher cases are in their own file and separate from tests.
